[tool.poetry]
name = "sandcat"
version = "0.1.0"
description = "A CCG prover"
authors = ["Masaya Taniguchi <ta2gch@gmail.com>"]
license = "Apache Software License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
z3-solver = "^4.12.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
