# sympy_stub.pyi
from typing import Literal, NotRequired

class Expr: ...

def Symbol(name: str) -> Expr: ...

def And(*args: Expr) -> Expr: ...

def Or(*args: Expr) -> Expr: ...

def Not(arg: Expr) -> Expr: ...

def Implies(lhs: Expr, rhs: Expr) -> Expr: ...

Solvers = Literal["z3", "minisat22", "dpll2", "dpll", "pycosat"] | None

SatRetval = Literal[False] | dict[Symbol, bool]

def satisfiable(expr: Expr, algorithm=NotRequired[Solvers]) -> SatRetval: ...
