# sympy_stub.pyi
from typing import Any

class Expr:
    ...

class Symbol(Expr):
    def __init__(self, name: str) -> None: ...

class And(Expr):
    def __init__(self, *args: Expr) -> None: ...

class Or(Expr):
    def __init__(self, *args: Expr) -> None: ...

class Not(Expr):
    def __init__(self, arg: Expr) -> None: ...

class Implies(Expr):
    def __init__(self, lhs: Expr, rhs: Expr) -> None: ...

def satisfiable(expr: Expr, **kwargs: Any) -> bool: ...
